DROP DATABASE IF EXISTS artPortalDB;
CREATE DATABASE IF NOT EXISTS artPortalDB CHARACTER SET utf8;   
USE artPortalDB;


DROP TABLE IF EXISTS role_names;
CREATE TABLE role_names (
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(45) NOT NULL, 
  PRIMARY KEY(id)
)ENGINE = InnoDB CHARACTER SET UTF8;


DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(45),
  surname VARCHAR(45),
  login VARCHAR(45) UNIQUE NOT NULL,
  psw VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  photoPath VARCHAR(145),
  commentAble TINYINT(1) NOT NULL DEFAULT 1,
  active TINYINT(1) NOT NULL DEFAULT 1,
  role_id BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY(id),
  FOREIGN KEY (role_id) REFERENCES role_names(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;


DROP TABLE IF EXISTS competitions;
CREATE TABLE competitions(
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(45) NOT NULL,
  description VARCHAR(4500) NOT NULL,
  startDate DATE,
  loadDeadline DATE,
  endDate DATE,
  winner_id BIGINT,
  PRIMARY KEY(id),
  FOREIGN KEY (winner_id) REFERENCES users(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;


DROP TABLE IF EXISTS presents;
CREATE TABLE presents(
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(45) NOT NULL,
  photoPath VARCHAR(145),
  description VARCHAR(4500),
  competition_id BIGINT,
  PRIMARY KEY(id),
  FOREIGN KEY (competition_id) REFERENCES competitions(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;


DROP TABLE IF EXISTS art_types;
CREATE TABLE art_types(
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(45) NOT NULL,
  PRIMARY KEY(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;


DROP TABLE IF EXISTS art_works;
CREATE TABLE art_works(
  id BIGINT AUTO_INCREMENT NOT NULL,
  name VARCHAR(145) UNIQUE NOT NULL,
  path VARCHAR(145) NOT NULL,
  loadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  approved TINYINT(1) NOT NULL DEFAULT 1,
  type_id BIGINT,
  user_id BIGINT,
  competition_id BIGINT,
  PRIMARY KEY(id),
  FOREIGN KEY (type_id) REFERENCES art_types(id),
  FOREIGN KEY (user_id) REFERENCES users(id),
  FOREIGN KEY (competition_id) REFERENCES competitions(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;


DROP TABLE IF EXISTS comments;
CREATE TABLE comments(
  id BIGINT AUTO_INCREMENT NOT NULL,
  commentText VARCHAR(1000) NOT NULL,
  loadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  work_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (work_id) REFERENCES art_works(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
)ENGINE = InnoDB CHARACTER SET UTF8;


DROP TABLE IF EXISTS voices;
CREATE TABLE voices(
  id BIGINT AUTO_INCREMENT NOT NULL,
  voiceValue INT NOT NULL,
  loadDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  work_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (work_id) REFERENCES art_works(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;


DROP TABLE IF EXISTS roles;
CREATE TABLE roles(
  id BIGINT AUTO_INCREMENT NOT NULL,
  login VARCHAR(45) NOT NULL, 
  role VARCHAR(45) NOT NULL, 
  PRIMARY KEY(id)
)ENGINE = InnoDB CHARACTER SET=UTF8;
